name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test || true

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          # Here you would add the command to build your Docker image, for example:
          # docker build -t my-image:latest .

      - name: Push Docker image
        run: |
          echo "Pushing Docker image..."
          # Here you would add the command to push your Docker image, for example:
          # echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username anithayeruva --password-stdin
          # docker push my-image:latest
